# Generated by Django 5.2 on 2026-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course_submitted', 'Курс отправлен на проверку'), ('course_published', 'Курс опубликован'), ('course_revision', 'Курс отправлен на доработку'), ('trainer_verified', 'Тренер верифицирован'), ('verification_requested', 'Запрос на верификацию'), ('course_deletion_approved', 'Удаление курса подтверждено'), ('course_deletion_rejected', 'Запрос на удаление отклонён')], max_length=30, verbose_name='Тип'),
        ),
    ]
