# Generated by Django 5.2 on 2026-02-04 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.UUIDField(verbose_name='ID контента')),
                ('content_type', models.CharField(choices=[('module_content', 'Контент модуля'), ('day_content', 'Контент дня')], max_length=30, verbose_name='Тип контента')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('watch_percent', models.PositiveSmallIntegerField(default=0, help_text='Для видео: процент просмотра', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент просмотра')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, help_text='payme, click, test и т.д.', max_length=50, verbose_name='Способ оплаты')),
                ('payment_id', models.CharField(blank=True, help_text='ID транзакции от провайдера', max_length=100, verbose_name='ID транзакции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('variant_locked', models.BooleanField(default=False, help_text='True после выбора варианта пользователем', verbose_name='Вариант заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'enrollments',
            },
        ),
    ]
