# Generated by Django 5.2 on 2026-02-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Заполняется после выбора пользователем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training.trainingvariant', verbose_name='Выбранный вариант'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='enrollments.enrollment', verbose_name='Покупка'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='enrollments_user_id_d469b8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='enrollments_course__711f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active'], name='enrollments_user_id_432aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_enrollment_per_user_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'content_id', 'content_type'), name='unique_progress_per_content'),
        ),
    ]
