# Generated by Django 5.2 on 2026-02-04 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gdrive_id', models.CharField(max_length=100, unique=True, verbose_name='Google Drive ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(choices=[('application/pdf', 'PDF'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG')], max_length=100, verbose_name='MIME тип')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('view_url', models.URLField(blank=True, help_text='URL для просмотра без возможности скачивания', max_length=500, verbose_name='URL для просмотра')),
                ('upload_status', models.CharField(choices=[('pending', 'Ожидает загрузки'), ('uploading', 'Загружается'), ('complete', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='users.trainer', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл Google Drive',
                'verbose_name_plural': 'Файлы Google Drive',
                'db_table': 'gdrive_files',
            },
        ),
        migrations.CreateModel(
            name='VimeoVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vimeo_id', models.CharField(help_text='ID видео на платформе Vimeo', max_length=50, unique=True, verbose_name='Vimeo ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('upload_status', models.CharField(choices=[('pending', 'Ожидает загрузки'), ('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('complete', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус загрузки')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Превью')),
                ('playback_url', models.URLField(blank=True, max_length=500, verbose_name='URL воспроизведения')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки приватности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to='users.trainer', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Видео Vimeo',
                'verbose_name_plural': 'Видео Vimeo',
                'db_table': 'vimeo_videos',
            },
        ),
    ]
