# Generated by Django 5.2 on 2026-02-04 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('is_rest_day', models.BooleanField(default=False, verbose_name='День отдыха')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'db_table': 'day_schedules',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='DayContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='Порядок отображения (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content_type', models.CharField(choices=[('video', 'Видео'), ('pdf', 'PDF'), ('image', 'Изображение')], max_length=20, verbose_name='Тип контента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gdrive_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_usages', to='storage.googledrivefile', verbose_name='Файл')),
                ('vimeo_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_usages', to='storage.vimeovideo', verbose_name='Видео')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='training.dayschedule', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Контент дня',
                'verbose_name_plural': 'Контент дней',
                'db_table': 'day_contents',
                'ordering': ['content_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Номер варианта')),
                ('name', models.CharField(help_text='Например: "2 раза в неделю"', max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, help_text='Вариант 1 всегда обязателен', verbose_name='Обязательный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_variants', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Вариант тренировок',
                'verbose_name_plural': 'Варианты тренировок',
                'db_table': 'training_variants',
                'ordering': ['variant_number'],
            },
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='Номер недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.trainingvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Неделя',
                'verbose_name_plural': 'Недели',
                'db_table': 'week_schedules',
                'ordering': ['week_number'],
            },
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.weekschedule', verbose_name='Неделя'),
        ),
        migrations.AddConstraint(
            model_name='trainingvariant',
            constraint=models.UniqueConstraint(fields=('course', 'variant_number'), name='unique_variant_per_course'),
        ),
        migrations.AddConstraint(
            model_name='trainingvariant',
            constraint=models.CheckConstraint(condition=models.Q(('variant_number__gte', 1), ('variant_number__lte', 3)), name='valid_variant_number'),
        ),
        migrations.AddConstraint(
            model_name='weekschedule',
            constraint=models.UniqueConstraint(fields=('variant', 'week_number'), name='unique_week_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='dayschedule',
            constraint=models.UniqueConstraint(fields=('week', 'day_of_week'), name='unique_day_per_week'),
        ),
    ]
