# Generated by Django 5.2 on 2026-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvariant',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='trainingvariant',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='trainingvariant',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='trainingvariant',
            name='name',
            field=models.CharField(help_text='Например: "2 раза в неделю"', max_length=100, verbose_name='Название (RU)'),
        ),
    ]
