# Generated by Django 5.2 on 2026-05-04 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingvariant_description_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycontent',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Порядок отображения (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порядок'),
        ),
    ]
