# Generated by Django 5.2 on 2026-02-04 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('users', '0003_alter_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_url', models.URLField(blank=True, max_length=500, verbose_name='Иконка/Фон')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.CharField(help_text='1-2 предложения об основном результате курса', max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, help_text='Поддерживает Markdown', verbose_name='Полное описание')),
                ('level', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('format', models.CharField(choices=[('home', 'Дома'), ('gym', 'В зале'), ('mixed', 'Смешанный')], default='home', max_length=20, verbose_name='Формат')),
                ('equipment', models.TextField(blank=True, help_text='Необходимое оборудование для курса', verbose_name='Оборудование')),
                ('target_weight_range', models.CharField(blank=True, help_text='Для какого веса предназначен курс', max_length=50, verbose_name='Диапазон веса')),
                ('language', models.CharField(default='ru', help_text='Код языка: ru, uz, en', max_length=10, verbose_name='Язык')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (UZS)')),
                ('duration_weeks', models.PositiveSmallIntegerField(default=4, verbose_name='Длительность (недель)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к ученику')),
                ('goals_text', models.TextField(blank=True, help_text='Цель в виде текста от тренера (Markdown)', verbose_name='Цель курса')),
                ('purchases_count', models.PositiveIntegerField(default=0, verbose_name='Количество покупок')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.category', verbose_name='Категория')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('training', 'Тренировки'), ('theory', 'Теория'), ('nutrition', 'Питание'), ('recovery', 'Восстановление')], max_length=20, verbose_name='Тип модуля')),
                ('priority', models.PositiveSmallIntegerField(help_text='От 1 до 5 звёзд, 5 = основной модуль', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритет')),
                ('is_primary', models.BooleanField(default=False, help_text='Автоматически true если priority=5', verbose_name='Основной модуль')),
                ('is_filled', models.BooleanField(default=False, help_text='Есть ли контент в модуле', verbose_name='Заполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курсов',
                'db_table': 'course_modules',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('content_type', models.CharField(choices=[('video', 'Видео'), ('pdf', 'PDF'), ('image', 'Изображение')], max_length=20, verbose_name='Тип контента')),
                ('is_preview', models.BooleanField(default=False, help_text='Показывать до покупки курса', verbose_name='Доступно для предпросмотра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gdrive_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_usages', to='storage.googledrivefile', verbose_name='Файл')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.coursemodule', verbose_name='Модуль')),
                ('vimeo_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_usages', to='storage.vimeovideo', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Контент модуля',
                'verbose_name_plural': 'Контент модулей',
                'db_table': 'module_contents',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['trainer'], name='courses_trainer_8c30f6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_categor_2870c7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='courses_categor_e366fa_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'type'], name='course_modu_course__67b1fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'type'), name='unique_module_type_per_course'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'priority'), name='unique_priority_per_course'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_favorite_per_user_course'),
        ),
    ]
