# Generated by Django 5.2 on 2026-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['course__title'], 'verbose_name': 'Модуль курса', 'verbose_name_plural': 'Модули курсов'},
        ),
        migrations.AddField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Обложка курса'),
        ),
    ]
