# Generated by Django 5.2 on 2026-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursemodule_options_course_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deletion_requested',
            field=models.BooleanField(default=False, help_text='Тренер запросил удаление, ожидает подтверждения админа', verbose_name='Запрос на удаление'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Обложка курса (URL)'),
        ),
    ]
