# Generated by Django 5.2 on 2026-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_deletion_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='full_description_uz',
            field=models.TextField(blank=True, verbose_name='Полное описание (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (UZ)'),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, help_text='Поддерживает Markdown', verbose_name='Полное описание (RU)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(help_text='1-2 предложения об основном результате курса', max_length=500, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На проверке'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название (RU)'),
        ),
    ]
