# Generated by Django 5.2 on 2026-05-14 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_revision_required_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена (UZS)'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='От 0 до 5, 5 = основной модуль', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='type',
            field=models.CharField(choices=[('training', 'Тренировки'), ('theory', 'Теория'), ('nutrition', 'Питание'), ('recovery', 'Восстановление'), ('sports_nutrition', 'Спортивное питание'), ('training_nuances', 'Нюансы тренировок')], max_length=20, verbose_name='Тип модуля'),
        ),
    ]
