# Generated by Django 5.2 on 2026-02-18 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_deletion_requested_alter_course_cover_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('click_trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Click Trans ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('prepared', 'Подготовлено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_transactions', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Click транзакция',
                'verbose_name_plural': 'Click транзакции',
                'db_table': 'click_transactions',
                'indexes': [models.Index(fields=['user', 'course'], name='click_trans_user_id_afe905_idx'), models.Index(fields=['click_trans_id'], name='click_trans_click_t_07cd0f_idx'), models.Index(fields=['status'], name='click_trans_status_1f2bf5_idx')],
            },
        ),
    ]
