# Generated by Django 5.2 on 2026-02-19 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_deletion_requested_alter_course_cover_url'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(verbose_name='Сумма (тийин)')),
                ('payme_trans_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Payme Trans ID')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='Состояние Payme')),
                ('cancel_reason', models.IntegerField(blank=True, null=True, verbose_name='Причина отмены')),
                ('create_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время создания (ms)')),
                ('perform_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время выполнения (ms)')),
                ('cancel_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время отмены (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Payme транзакция',
                'verbose_name_plural': 'Payme транзакции',
                'db_table': 'payme_transactions',
                'indexes': [models.Index(fields=['user', 'course'], name='payme_trans_user_id_cc0084_idx'), models.Index(fields=['payme_trans_id'], name='payme_trans_payme_t_1aa6c7_idx'), models.Index(fields=['state'], name='payme_trans_state_1a024d_idx')],
            },
        ),
    ]
