# Generated by Django 5.2 on 2026-02-04 09:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
