# Generated by Django 5.2 on 2026-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='intro_video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Видео о себе'),
        ),
    ]
