# Generated by Django 5.2 on 2026-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_trainer_career_start_year'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='user_consen_user_id_4f2eed_idx',
            old_name='user_consents_user_type_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Устаревшее поле — используйте career_start_year', verbose_name='Стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='consent_type',
            field=models.CharField(choices=[('registration', 'Пользовательское соглашение + Политика конфиденциальности'), ('privacy', 'Обработка персональных данных'), ('marketing', 'Маркетинговые уведомления'), ('medical', 'Медицинский дисклеймер'), ('payment_rules', 'Правила оплаты и возврата'), ('trainer_agreement', 'Договор-оферта для тренеров')], max_length=20, verbose_name='Тип согласия'),
        ),
    ]
